Repository woorifisa-projects/GoodFriends, pull requests merged in 2023-08, with the labels that each got.

#14 chore: main과 develop 브랜치 동기화
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/README.md
  frontend/cypress.config.js
  frontend/cypress/e2e/example.cy.ts
  frontend/cypress/e2e/jsconfig.json
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/env.d.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/stores/counter.ts
  frontend/src/views/HomeView.vue
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/tsconfig.vitest.json
  frontend/vite.config.ts
  frontend/vitest.config.ts
Labels: 프로젝트 세팅

#29 [공통컴포넌트] 헤더와 푸터를 구현한다.
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/images/blog.png
  frontend/src/assets/images/github.png
  frontend/src/assets/main.css
  frontend/src/assets/tmp/images/image.png
  frontend/src/layouts/DefaultFooter.vue
  frontend/src/layouts/DefaultHeader.vue
  frontend/src/layouts/DefaultLayout.vue
Labels: 프론트엔드, 기능, 디자인

#37 [프로필 페이지] 프로필 페이지를 구현한다.
  frontend/src/App.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/layouts/DefaultHeader.vue
  frontend/src/layouts/DefaultLayout.vue
  frontend/src/router/index.ts
  frontend/src/views/ProfileView.vue
Labels: 프론트엔드, 기능, 디자인

#40 [프로필 페이지] 구매 페이지 및 판매 페이지를 구현한다.
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/router/index.ts
  frontend/src/types/Profile.ts
  frontend/src/views/PurchaseView.vue
  frontend/src/views/SellView.vue
Labels: 프론트엔드, 기능, 디자인

#39 Create SECURITY.md
  SECURITY.md
Labels: 문서 작성

#42 [사용자 정보] 유저 테이블을 구현
  backend/src/main/java/woorifisa/goodfriends/backend/BackendApplication.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/Nickname.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/exception/InvalidNicknameException.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/exception/InvalidUserException.java
Labels: 기능, 백엔드

#43 [관리자 페이지] 로그인 페이지를 구현한다.
  frontend/src/router/index.ts
  frontend/src/views/AdminLogin.vue
Labels: 프론트엔드, 기능, 디자인

#45 소셜 로그인을 이용하여 로그인 기능을 구현한다.
  backend/src/main/java/woorifisa/goodfriends/backend/BackendApplication.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/controller/OAuthLoginController.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/GoogleOAuthClient.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/service/OAuthLoginService.java
Labels: 기능, 백엔드

#46 [관리자] 자체 로그인 기능을 구현한다.
  backend/build.gradle
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/exception/InvalidAdminException.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/JwtFilter.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/JwtTokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/webconfig/AuthenticationConfig.java
Labels: 기능, 백엔드

#49 MySQL 관련 yml 파일 .gitignore에 추가
  .gitignore
  backend/src/main/resources/application-test.yml
Labels: 백엔드, 프로젝트 세팅

#51 프론트엔드 EC2서버 배포하기 위해 package.json 수정
  frontend/package.json
Labels: 프론트엔드, 인프라

#56 [상품 페이지] 상품 등록 및 수정 페이지를 구현한다.
  frontend/src/assets/base.css
  frontend/src/assets/images/delete.png
  frontend/src/components/product/EditProduct.vue
  frontend/src/router/index.ts
  frontend/src/types/product.ts
  frontend/src/utils/File.ts
  frontend/src/utils/format.ts
  frontend/src/views/AddProduct.vue
  frontend/src/views/EditProductView.vue
Labels: 프론트엔드, 기능, 디자인

#59 스프링 부트 버전 변경 및 테스트 관련 자동 설정 기능 제공
  backend/build.gradle
  backend/src/test/java/woorifisa/sut/backend/BackendApplicationTests.java
Labels: 백엔드, 프로젝트 세팅

#52 백엔드 관리자 자체 로그인 기능을 프론트엔드 로그인 페이지와 연동하여 동작되도록 구현한다.
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/webconfig/WebConfig.java
  backend/src/main/resources/application-test.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/adminLogin.ts
  frontend/src/views/AdminLogin.vue
Labels: 프론트엔드, 기능, 백엔드

#65 [관리자 페이지] 사이드바 컴포넌트를 구현한다.
  frontend/src/layouts/admin/DefaultSide.vue
Labels: 프론트엔드, 디자인

#64 [사용자 페이지] 상품 상세 페이지를 구현한다.
  frontend/src/router/index.ts
  frontend/src/views/HomeView.vue
  frontend/src/views/ProductView.vue
Labels: 프론트엔드, 기능, 디자인

#66 Feature/19(사용자가 중고 물품을 등록해서 판매하는 기능 구현)
  backend/build.gradle
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/webconfig/AuthenticationConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/controller/SetUpController.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/File.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductCategory.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImage.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductStatus.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/request/ProductSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductSaveResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/Nickname.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/exception/NoSuchUserException.java
Labels: 기능, 백엔드

#69 Refactor/68(html 내부 문자열 외부 파일로 분리)
  frontend/src/assets/tmp/images/logo.png
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/images.ts
  frontend/src/constants/strings/header.ts
  frontend/src/constants/strings/product.ts
  frontend/src/constants/strings/profile.ts
  frontend/src/layouts/DefaultFooter.vue
  frontend/src/layouts/DefaultHeader.vue
  frontend/src/router/index.ts
  frontend/src/views/AddProductView.vue
  frontend/src/views/ProductView.vue
  frontend/src/views/ProfileView.vue
Labels: 리팩터링, 프론트엔드

#75 Feat/70 (관리자 페이지에서 사용할 공통 컴포넌트 구현)
  frontend/src/components/CommonTable.vue
  frontend/src/types/table.ts
Labels: 프론트엔드, 기능, 디자인

#78 Feat/77(공통 컴포넌트 모달창구현)
  frontend/src/components/CommonModal.vue
Labels: 프론트엔드, 기능, 디자인

#80 feat/79(404페이지 구현)
  frontend/src/router/index.ts
  frontend/src/views/NotFoundView.vue
Labels: 프론트엔드, 기능, 디자인

#83 [관리자 페이지] 사용자 정보수정 페이지를 구현한다
  frontend/src/constants/strings/admin.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/views/EditUserInfoView.vue
Labels: 프론트엔드, 디자인

#84 Feat/81(반응형 구현)
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/layouts/DefaultFooter.vue
  frontend/src/layouts/DefaultHeader.vue
  frontend/src/layouts/DefaultLayout.vue
  frontend/src/types/product.ts
  frontend/src/views/HomeView.vue
  frontend/src/views/NotFoundView.vue
  frontend/src/views/ProductView.vue
  frontend/src/views/ProfileView.vue
  frontend/src/views/PurchaseView.vue
Labels: 프론트엔드, 기능, 디자인

#86 Feature/13(구글 소셜 로그인 기능 구현)
  .gitignore
  backend/build.gradle
  backend/gradlew
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/OAuthClient.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/OAuthUri.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/controller/OAuthLoginController.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/AuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/GoogleOAuthClient.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/OAuthUser.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/request/TokenRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/response/AccessTokenResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/response/OAuthUriResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/event/UserSavedEvent.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/service/OAuthLoginService.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/AuthenticationConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/PropertiesConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/WebConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/properties/GoogleProperties.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/webconfig/WebConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/controller/SetUpController.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/dto/GoogleTokenResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/client/GoogleOAuthClient.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/dto/UserInfo.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/exception/OAuthException.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/uri/GoogleOAuthUri.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
Labels: 기능, 백엔드

#91 Feat/85(주문 모달창 구현)
  frontend/src/components/OrderModal.vue
  frontend/src/constants/strings/product.ts
  frontend/src/utils/date.ts
  frontend/src/views/ProductView.vue
Labels: 프론트엔드, 기능, 디자인

#94 Feat/92(주문서 목록 페이지 구현)
  frontend/src/constants/strings/product.ts
  frontend/src/router/index.ts
  frontend/src/views/OrderView.vue
  frontend/src/views/ProductView.vue
Labels: 프론트엔드, 디자인

#98 Feature/88([관리자 페이지] 상품 등록/수정 페이지를 개발한다)
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/constants/strings/admin.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/views/AddProductByAdminView.vue
  frontend/src/views/EditProductByAdminView.vue
Labels: 프론트엔드, 디자인

#99 chore: gradle-wrapper .gitignore 제거
  .gitignore
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
Labels: 인프라, 백엔드, 프로젝트 세팅

#101 Feat/95(프로필 수정 기능 추가)
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/strings/profile.ts
  frontend/src/utils/File.ts
  frontend/src/utils/format.ts
  frontend/src/utils/validation.ts
  frontend/src/views/ProfileView.vue
Labels: 프론트엔드, 기능, 디자인

#96 Feature/90(전체 상품 조회 및 상세 상품 조회 기능을 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductSaveResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductUpdateResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Labels: 기능, 백엔드

#93 Feature/87(로그인한 유저에 인증/인가를 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/LoginUser.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/EmptyAuthorizationHeaderException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/InvalidTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthenticationPrincipal.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthenticationPrincipalArgumentResolver.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthorizationExtractor.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/WebConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/application/UserService.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/dto/response/UserResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/presentation/UserController.java
Labels: 기능, 백엔드

#104 refactor: 파일 위치 변경
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/layouts/user/DefaultFooter.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/layouts/user/DefaultLayout.vue
  frontend/src/router/index.ts
  frontend/src/views/admin/AddProductByAdminView.vue
  frontend/src/views/admin/AdminLogin.vue
  frontend/src/views/admin/EditProductByAdminView.vue
  frontend/src/views/admin/EditUserInfoView.vue
  frontend/src/views/user/AddProductView.vue
  frontend/src/views/user/EditProductView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/NotFoundView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 리팩터링, 프론트엔드

#106 Feat/102(프로필에서 상품 상태에 따른 필터링)
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/FilterList.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/types/product.ts
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 프론트엔드, 기능, 디자인

#110 FIX/109(파일명 변경)
  frontend/src/types/profile.ts
  frontend/src/utils/file.ts
Labels: 버그, 프론트엔드

#111 Feature/105([관리자 페이지] 로그 관리 페이지를 개발한다.)
  frontend/src/components/CommonTable.vue
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/views/admin/ManageLogView.vue
Labels: 프론트엔드, 기능, 디자인

#108 Fix/107(배너 뒤로가기 버튼 오류 수정)
  frontend/src/views/user/HomeView.vue
Labels: 버그, 프론트엔드, 버그 처리

#115 Feature/97(s3생성하여 상품 이미지 저장)
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/src/main/java/woorifisa/goodfriends/backend/global/application/S3Service.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/S3Config.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/FileUtils.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImage.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImageRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/request/ProductSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/request/ProductUpdateRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductSaveResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductUpdateResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Labels: 리팩터링, 기능, 백엔드

#119 Feature/118([관리자 페이지] 신고 관리 페이지를 개발한다.)
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/views/admin/ManageDeclarationView.vue
Labels: 프론트엔드, 기능, 디자인

#123 Feature/121(생성일자, 수정일자를 저장하는 클래스 생성)
  backend/src/main/java/woorifisa/goodfriends/backend/BackendApplication.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/common/BaseCreateTimeEntity.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/common/BaseTimeEntity.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
Labels: 리팩터링, 기능, 백엔드

#117 Feature/116([관리자 페이지] Header 컴포넌트를 수정한다)
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/views/admin/AddProductByAdminView.vue
  frontend/src/views/admin/EditProductByAdminView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인

#120 Feature/114([관리자 페이지] 사용자 관리 페이지를 개발한다.)
  frontend/src/components/CommonTable.vue
  frontend/src/constants/strings/admin.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/views/admin/EditUserInfoView.vue
  frontend/src/views/admin/ManageUserView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인

#125 Feat/113(디자인 및 색상 변경)
  frontend/src/assets/main.css
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/FilterList.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/product.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/layouts/user/DefaultLayout.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/NotFoundView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 프론트엔드, 디자인

#127 Feature/126(DB 오류를 수정하기 위해 테이블명을 변경한다.)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/common/BaseTimeEntity.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/File.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImage.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
Labels: 백엔드, 버그 처리

#129 Feature/122 (상품 등록/조회/수정/삭제 기능을 리펙토링한다)
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/FileUtils.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImageRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductUpdateResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NoSuchImageFileException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NoSuchProductException.java
Labels: 리팩터링, 백엔드

#131 Feature/130([관리자 페이지] 사이드바 화면 분할 오류를 수정한다.)
  frontend/src/layouts/admin/DefaultSide.vue
Labels: 버그

#132 Feat/128(주소찾기 API 연결)
  frontend/index.html
  frontend/src/components/AddressAPI.vue
  frontend/src/constants/strings/profile.ts
  frontend/src/types/profile.ts
  frontend/src/views/user/profile/ProfileView.vue
Labels: 프론트엔드, 기능

#136 Style/135(디자인 및 변경된 요구사항 반영
  frontend/index.html
  frontend/public/favicon.ico
  frontend/src/assets/main.css
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/strings/profile.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 프론트엔드, 디자인

#143 Feature/76(액세스 토큰과 리프레시 토큰을 모두 발급하는 기능 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenResponseHandler.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenProvider.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/InMemoryAuthTokenRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthTokenRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/TokenRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/OAuthUser.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundOAuthTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/dto/GoogleTokenResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/infrastructure/oauth/client/GoogleOAuthClient.java
Labels: 기능, 백엔드

#145 Feature/124([관리자 페이지] 상품 관리 페이지를 개발한다.)
  frontend/src/components/CommonTable.vue
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/router/index.ts
  frontend/src/types/product.ts
  frontend/src/views/admin/EditProductByAdminView.vue
  frontend/src/views/admin/ManageProductView.vue
  frontend/src/views/admin/ManageUserView.vue
Labels: 프론트엔드, 기능, 디자인

#149 Feature/148([관리자 페이지] 사용자 관리 상세 페이지에 계정 삭제버튼을 추가한다.)
  frontend/src/constants/strings/admin.ts
  frontend/src/views/admin/EditUserInfoView.vue
Labels: 프론트엔드, 기능, 디자인

#150 Docs/146(리드미를 수정한다)
  README.md
Labels: 문서 작성

#151 Feature/141([관리자] 상품 등록/조회/수정/삭제 기능을 구현한다.)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/Admin.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/AdminLoginRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/TokenResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/AuthenticationConfig.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Labels: 기능, 백엔드

#152 Feat/147(사용자 로그인 API 요청)
  .gitignore
  frontend/src/apis/index.ts
  frontend/src/apis/userLogin.ts
  frontend/src/components/LoadingIcon.vue
  frontend/src/constants/strings/error.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/router/index.ts
  frontend/src/stores/userInfo.ts
  frontend/src/views/user/ErrorView.vue
  frontend/src/views/user/ReceiveCodeView.vue
Labels: 프론트엔드, 기능

#157 Feature/76(리프레시 토큰을 통해 새로운 액세스 토큰을 발급)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/TokenCreator.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/AuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/dto/request/TokenRenewalRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
Labels: 기능, 백엔드

#158 Feat/155(상품 전체 조회 api 연결)
  frontend/src/apis/product.ts
  frontend/src/components/AddressAPI.vue
  frontend/src/components/CategoryList.vue
  frontend/src/components/CommonBanner.vue
  frontend/src/components/OrderModal.vue
  frontend/src/components/ProductCard.vue
  frontend/src/constants/category.ts
  frontend/src/constants/strings/error.ts
  frontend/src/types/product.ts
  frontend/src/views/user/ErrorView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/NotFoundView.vue
Labels: 프론트엔드, 기능

#159 Feature/153([관리자 페이지] 사용자 정보 수정 페이지 구조를 수정한다. )
  frontend/src/constants/strings/admin.ts
  frontend/src/views/admin/EditUserInfoView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인

#160 Feature/139(관리자 로그인 수정)
  frontend/src/apis/adminLogin.ts
  frontend/src/stores/admin.ts
  frontend/src/views/admin/AdminLogin.vue
  frontend/src/views/user/ReceiveCodeView.vue
Labels: 리팩터링, 프론트엔드, 기능

#162 Feature/161([관리자 페이지] 신고관리 페이지 테이블에 표출되는 컬럼을 수정/추가한다. )
  frontend/src/views/admin/ManageDeclarationView.vue
Labels: 리팩터링, 프론트엔드

#164 Feature/163(로그아웃시 액세스 토큰과 리프레시 토큰을 만료시키는 기능을 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthTokenRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
Labels: 기능, 백엔드

#168 Feature/154(상품 주문 등록/조회 기능을 구현한다)
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/Order.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/request/OrderSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/response/OrderViewAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/exception/AlreadyOrderedException.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java
Labels: 기능, 백엔드

#172 fix/171(배너 이미지 계속 요청하는 오류 수정)
  frontend/src/components/CommonBanner.vue
Labels: 버그, 프론트엔드

#174 Feature/169([관리자 페이지] 신고 관리 상세페이지 개발한다. )
  frontend/src/constants/strings/admin.ts
  frontend/src/router/index.ts
  frontend/src/views/admin/DeclarationDetailView.vue
Labels: 프론트엔드, 기능, 디자인

#177 Feature/167(프로필 정보를 수정하는 기능 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/global/common/BaseCreateTimeEntity.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/ProfileRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/request/ProfileUpdateRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProfileUpdateResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/application/UserService.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
Labels: 기능, 백엔드

#176 Refactor/175(API 요청 코드 수정)
  frontend/src/apis/admin/login.ts
  frontend/src/apis/adminLogin.ts
  frontend/src/apis/product.ts
  frontend/src/apis/user/login.ts
  frontend/src/apis/user/product.ts
  frontend/src/apis/userLogin.ts
  frontend/src/components/AddressAPI.vue
  frontend/src/components/CommonTable.vue
  frontend/src/components/EmptyProduct.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/FilterList.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/apiType.ts
  frontend/src/constants/strings/product.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/types/api.ts
  frontend/src/types/product.ts
  frontend/src/types/profile.ts
  frontend/src/types/table.ts
  frontend/src/utils/goPage.ts
  frontend/src/views/admin/AdminLogin.vue
  frontend/src/views/admin/ManageProductView.vue
  frontend/src/views/admin/ManageUserView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/ReceiveCodeView.vue
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 리팩터링, 프론트엔드, 기능

#181 Feature/180([관리자 페이지] 신고 관리 페이지에서 신고 상세 페이지로 이동을 구현한다.)
  frontend/src/views/admin/ManageDeclarationView.vue
Labels: 리팩터링, 프론트엔드, 기능
