Repository woorifisa-projects/GoodFriends, pull requests merged in 2023-09, with the labels that each got.

#183 Feature/173(로그아웃 및 토큰 재발급 API 연결)
  frontend/src/apis/index.ts
  frontend/src/apis/user/login.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/strings/header.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/stores/userInfo.ts
  frontend/src/types/api.ts
  frontend/src/views/user/ReceiveCodeView.vue
Labels: 프론트엔드, 기능

#187 Feature/156(로그인한 유저에 한한여 상품 등록/수정/삭제 가능하도록 기능 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/EmptyAuthorizationHeaderException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundOAuthTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Labels: 기능, 백엔드

#186 fix/185(최초 회원가입한 유저가 일부 프로필 정보가 없을 경우 새로 생성해서 값을 넣어주도록 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
Labels: 리팩터링, 백엔드

#188 Feature/184(사용자 로그기록 추출하는 API를 구현한다.)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserLogRecordResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
Labels: 기능, 백엔드

#195 Fix/193(로그 조회 누락된 소스파일 업로드)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserLogRecordsResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/exception/NotFoundAdminException.java
Labels: 백엔드, 버그 처리

#197 Fix/196(AdminController의 TokenResponse 임포트 제거)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
Labels: 백엔드, 버그 처리

#199 Feature/191(상품 전체/상세 조회 시 상품을 등록한 사람의 프로필 정보가 보이도록 한다.)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
Labels: 기능, 백엔드

#200 Refactor/192(Set-Cookie로 설정한 리프레시 토큰과 관련된 로직을 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenResponseHandler.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
Labels: 리팩터링, 백엔드

#205 Feature/204(관리자 아이디로 권한 확인 하도록 코드 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
Labels: 백엔드, 버그 처리

#207 Feature/206(예외 처리를 정의하는 하나의 ControllerAdvice 클래스를 생성하여 관리)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/EmptyAuthorizationHeaderException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/InvalidTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundOAuthTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/exception/NotFoundTokenException.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/config/utils/FileUtils.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/dto/ErrorReportRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/dto/ErrorResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/exception/AlreadyOrderedException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NoSuchProductException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NotFoundImageFileException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NotFoundProductException.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/application/UserService.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/exception/NoSuchUserException.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/exception/NotFoundUserException.java
  backend/src/test/java/woorifisa/goodfriends/backend/integration/BackendApplicationTests.java
Labels: 리팩터링, 기능, 백엔드

#201 Feature/189(사용자 정보 수정,제거 API 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/domain/AdminRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/UserUpdateRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/OAuthToken.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/Order.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
Labels: 리팩터링, 기능, 백엔드

#208 Feature/170(상품 API 프론트엔드에 연결
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  frontend/src/apis/user/product.ts
  frontend/src/components/product/EditProduct.vue
  frontend/src/types/product.ts
  frontend/src/utils/file.ts
  frontend/src/utils/validation.ts
  frontend/src/views/user/ProductView.vue
Labels: 프론트엔드, 기능

#212 Fix/210(사용자 로그아웃 코드 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthService.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenResponseHandler.java
  backend/src/main/java/woorifisa/goodfriends/backend/auth/presentation/AuthController.java
  frontend/src/apis/user/login.ts
  frontend/src/layouts/user/DefaultHeader.vue
Labels: 프론트엔드, 백엔드, 버그 처리

#211 Feature/209 관리자 로그 관리 api와 프론트단과 연동
  frontend/src/apis/admin/log.ts
  frontend/src/constants/apiType.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/types/api.ts
  frontend/src/views/admin/ManageLogView.vue
  frontend/src/views/admin/ManageUserView.vue
Labels: 리팩터링, 프론트엔드, 기능

#215 setting: Spring rest docs 설치
  backend/build.gradle
Labels: 백엔드, 프로젝트 세팅

#216 Refactor/213(프론트엔드 interface 리펙토링)
  frontend/src/apis/admin/log.ts
  frontend/src/apis/admin/login.ts
  frontend/src/apis/user/login.ts
  frontend/src/apis/user/product.ts
  frontend/src/apis/user/profile.ts
  frontend/src/assets/images/logo.png
  frontend/src/assets/tmp/images/logo.png
  frontend/src/components/ProductCard.vue
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/constants/images.ts
  frontend/src/layouts/user/DefaultFooter.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/stores/userInfo.ts
  frontend/src/types/api.ts
  frontend/src/types/log.ts
  frontend/src/types/login.ts
  frontend/src/types/product.ts
  frontend/src/types/profile.ts
  frontend/src/utils/validation.ts
  frontend/src/views/admin/ManageProductView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/ProductView.vue
Labels: 리팩터링, 프론트엔드

#221 Feature/217(사용자 관리 전체조회 API 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserInfoResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
Labels: 기능, 백엔드

#230 Feature/228(로그인하지 않은 사용자 페이지 이동 제한)
  frontend/src/apis/admin/log.ts
  frontend/src/apis/admin/login.ts
  frontend/src/apis/user/login.ts
  frontend/src/apis/user/product.ts
  frontend/src/apis/user/profile.ts
  frontend/src/components/product/EditProduct.vue
  frontend/src/constants/apiType.ts
  frontend/src/constants/strings/error.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/router/index.ts
  frontend/src/types/api.ts
  frontend/src/views/admin/AdminLogin.vue
  frontend/src/views/user/ErrorView.vue
  frontend/src/views/user/NotFoundView.vue
  frontend/src/views/user/ReceiveCodeView.vue
Labels: 프론트엔드, 기능

#232 Feature/229(상품 카테고리별 조회 및 검색 기능 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java
  frontend/src/apis/user/product.ts
  frontend/src/views/user/HomeView.vue
Labels: 프론트엔드, 기능, 백엔드

#236 Fix/235 front build error
  backend/src/main/java/woorifisa/goodfriends/backend/declaration/application/DeclarationService.java
  frontend/src/apis/user/product.ts
Labels: 프론트엔드, 백엔드, 버그 처리

#240 Feature/238(사용자, 관리자 전체 API 통일화해서 정의)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/declaration/application/DeclarationService.java
  backend/src/main/java/woorifisa/goodfriends/backend/declaration/domain/DeclarationRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/declaration/dto/request/DeclarationSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/declaration/presentation/DeclarationController.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/application/ReportService.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/Content.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/Report.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/ReportCategory.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/ReportRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/ReportStatus.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/dto/request/ReportSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/exception/ReportException.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/presentation/ReportController.java
  frontend/src/apis/admin/log.ts
  frontend/src/apis/user/product.ts
Labels: 리팩터링, 프론트엔드, 백엔드

#241 Feature/238(사용자 및 관리자 추가 API url 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  frontend/src/apis/user/profile.ts
Labels: 리팩터링, 프론트엔드, 백엔드

#242 Feat/225(관리자가 신고한 중고 물품을 조회하는 기능 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/presentation/AdminController.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/ReportRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/dto/response/ReportResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/dto/response/ReportsResponse.java
Labels: 기능, 백엔드

#244 Feature/226(사용자 관리,상세 페이지 API 연동)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/request/UserUpdateRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserInfoResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  frontend/src/apis/admin/allUserInfo.ts
  frontend/src/constants/strings/admin.ts
  frontend/src/types/allUserInfo.ts
  frontend/src/views/admin/DeclarationDetailView.vue
  frontend/src/views/admin/EditUserInfoView.vue
  frontend/src/views/admin/ManageDeclarationView.vue
  frontend/src/views/admin/ManageLogView.vue
  frontend/src/views/admin/ManageUserView.vue
Labels: 리팩터링, 프론트엔드, 디자인, 백엔드

#246 Feature/243(프로필 정보에 계좌종류, 계좌번호 추가하여 기존 기능 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/AccountType.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/request/ProfileUpdateRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProfileViewResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
Labels: 기능, 백엔드

#247 Feature/233(상품을 거래하는 API를 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/ConfirmStatus.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/Order.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/request/OrderSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/response/OrderViewAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/response/OrderViewOneResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/exception/NotFoundOrderException.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/dto/response/UserDealResponse.java
Labels: 기능, 백엔드

#250 Fix/248 (AdminSerice 클래스 관리자 관련 메소드 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  frontend/src/views/admin/ManageProductView.vue
Labels: 리팩터링, 프론트엔드, 백엔드

#249 Style/231(사용자 페이지 UI/UX 수정)
  frontend/src/components/CategoryList.vue
  frontend/src/components/CommonBanner.vue
  frontend/src/components/CommonModal.vue
  frontend/src/components/ConfirmModal.vue
  frontend/src/components/OrderModal.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/product.ts
  frontend/src/constants/strings/profile.ts
  frontend/src/layouts/user/DefaultFooter.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/layouts/user/DefaultLayout.vue
  frontend/src/types/dynamic.ts
  frontend/src/types/order.ts
  frontend/src/types/profile.ts
  frontend/src/utils/file.ts
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 프론트엔드, 디자인

#254 Feat/251(수정된 프로필 API 연동)
  frontend/src/apis/user/login.ts
  frontend/src/apis/user/product.ts
  frontend/src/apis/user/profile.ts
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/account.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/stores/userInfo.ts
  frontend/src/types/profile.ts
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 리팩터링, 프론트엔드, 기능

#256 Feature/253([관리자] 사용자 관리 페이지와 신고 페이지의 부분 스타일 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/admin/dto/response/UserInfoResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/Report.java
  frontend/src/apis/user/login.ts
  frontend/src/constants/strings/admin.ts
  frontend/src/types/allUserInfo.ts
  frontend/src/views/admin/DeclarationDetailView.vue
  frontend/src/views/admin/EditUserInfoView.vue
  frontend/src/views/admin/ManageUserView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인, 백엔드

#260 Feature/245(상품 관리 페이지의 목록 조회 API 연동)
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductImageRepository.java
  frontend/src/apis/admin/adminProduct.ts
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/views/admin/ManageProductView.vue
Labels: 프론트엔드, 기능

#261 Feature/224(사용자 신고 등록 페이지 구현)
  frontend/src/constants/strings/report.ts
  frontend/src/router/index.ts
  frontend/src/views/user/ProductReportContentView.vue
  frontend/src/views/user/ProductReportView.vue
Labels: 프론트엔드, 기능, 디자인

#266 Feature/252 (휴대폰 인증 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/application/SmsService.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/domain/CreatePhoneAuthNum.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/domain/CreateSignature.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/dto/MessagesDto.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/dto/request/Request.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/dto/request/SmsRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/dto/response/SmsResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/phoneAuth/presentation/SmsController.java
Labels: 리팩터링, 기능, 백엔드

#268 Style/259(사용자 페이지 UI/UX 수정)
  frontend/src/assets/base.css
  frontend/src/assets/main.css
  frontend/src/assets/tmp/images/banner4.png
  frontend/src/components/AddressAPI.vue
  frontend/src/components/CategoryList.vue
  frontend/src/components/CommonBanner.vue
  frontend/src/components/CommonModal.vue
  frontend/src/components/ConfirmModal.vue
  frontend/src/components/EmptyProduct.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/OrderModal.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/FilterList.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/defaultInput.ts
  frontend/src/constants/strings/product.ts
  frontend/src/constants/strings/profile.ts
  frontend/src/layouts/user/DefaultFooter.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/layouts/user/DefaultLayout.vue
  frontend/src/utils/image.ts
  frontend/src/views/admin/ManageProductView.vue
  frontend/src/views/user/ErrorView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 리팩터링, 프론트엔드, 디자인

#270 Feature/262(구매 목록, 판매 목록 API 구현)
  .gitignore
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewsAllResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProductViewPurchaseList.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProductViewSellList.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProductViewsPurchaseList.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProductViewsSellList.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java
Labels: 기능, 백엔드

#272 Feature/271(구매목록, 판매목록 api 연동)
  frontend/src/apis/user/profile.ts
  frontend/src/components/profile/FilterList.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/product.ts
  frontend/src/types/product.ts
  frontend/src/types/profile.ts
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 프론트엔드, 기능

#264 Feature/263(신고 API 연동 구현 및 디자인 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/offender/domain/Offender.java
  backend/src/main/java/woorifisa/goodfriends/backend/offender/domain/OffenderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/application/ReportService.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/Report.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/dto/request/ReportSaveRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/presentation/BoardReportController.java
  frontend/src/apis/user/report.ts
  frontend/src/constants/reportCategory.ts
  frontend/src/constants/strings/report.ts
  frontend/src/router/index.ts
  frontend/src/types/report.ts
  frontend/src/utils/validation.ts
  frontend/src/views/user/BoardReportView.vue
  frontend/src/views/user/ProductReportContentView.vue
  frontend/src/views/user/ProductReportView.vue
  frontend/src/views/user/ProductView.vue
Labels: 리팩터링, 프론트엔드, 기능, 백엔드

#276 Fix/273(프로필 페이지 디자인 오류 수정)
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/product.ts
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 프론트엔드, 디자인, 버그 처리

#277 Feature/275(상품 조회 페이지네이션 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
Labels: 기능, 백엔드

#278 Feature/269(프로필 페이지 휴대폰 인증 API 연동)
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/ProfileRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/exception/AlreadyExitPhoneProfile.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/exception/NotFoundProfile.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/application/SmsService.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/domain/CreatePhoneAuthNum.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/domain/CreateSignature.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/dto/MessagesDto.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/dto/request/Request.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/dto/request/SmsRequest.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/dto/response/SmsResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/sms/presentation/SmsController.java
  frontend/src/apis/user/profile.ts
  frontend/src/components/PhoneAuthAPI.vue
  frontend/src/constants/account.ts
  frontend/src/constants/strings/defaultInput.ts
  frontend/src/constants/strings/profile.ts
  frontend/src/types/profile.ts
  frontend/src/views/user/profile/ProfileView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인, 백엔드

#279 Feature/274(부정행위자로 등록된 유저는 거래하지 못하도록 로직 추가)
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/offender/domain/OffenderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/Order.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/NotAccessProduct.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  frontend/src/apis/user/profile.ts
  frontend/src/utils/validation.ts
Labels: 리팩터링, 기능, 백엔드

#285 Feature/280 프로필 상단 배너의 인증뱃지, 거래횟수, 신고횟수 표시 API를 구현
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/ProductRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/dto/response/ProfileBannerResponse.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/presentation/ProfileController.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/UserRepository.java
  frontend/src/components/PhoneAuthAPI.vue
Labels: 기능, 백엔드

#288 Test/265(구글 소셜 로그인/회원가입에 대한 단위 테스트코드 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/domain/AuthToken.java
  backend/src/test/java/woorifisa/goodfriends/backend/auth/application/AuthTokenCreatorTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/auth/application/JwtTokenProviderTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/auth/domain/AuthTokenTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/auth/domain/OAuthTokenTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/annotation/ServiceTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/config/ExternalApiConfig.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/OAuthFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/UserFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/infrastructure/oauth/client/StubOAuthClient.java
Labels: 백엔드, 테스트

#295 Feature/293( API 호출 후 페이지 이동 구현 )
  frontend/src/components/CategoryList.vue
  frontend/src/components/CommonBanner.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/layouts/user/DefaultFooter.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/views/user/BoardReportView.vue
Labels: 프론트엔드, 기능

#297 Refactor/294(에러 메시지 내용 수정)
  frontend/src/components/product/EditProduct.vue
  frontend/src/utils/validation.ts
  frontend/src/views/user/BoardReportView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 리팩터링, 프론트엔드

#300 Feature/299(휴대폰 번호 중복 확인 로직 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/profile/application/ProfileService.java
Labels: 리팩터링, 기능, 백엔드

#298 Test/286(상품 테스트 코드 작성)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/domain/Product.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/exception/InvalidDescriptionException.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/presentation/ProductController.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/ProductFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/ProfileFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/product/application/ProductServiceTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/product/domain/ProductTest.java
Labels: 백엔드, 테스트

#289 Test/287(회원 및 프로필에 대한 단위 테스트 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/profile/domain/Profile.java
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/ProfileFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/UserFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/profile/application/ProfileServiceTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/profile/domain/ProfileTest.java
  backend/src/test/java/woorifisa/goodfriends/backend/user/domain/UserTest.java
Labels: 백엔드, 테스트

#302 Feature/296(사용자 페이지 ui 수정)
  frontend/src/assets/images/banner1.png
  frontend/src/assets/images/banner2.png
  frontend/src/assets/tmp/images/banner1.jpeg
  frontend/src/assets/tmp/images/banner2.jpeg
  frontend/src/assets/tmp/images/banner3.jpeg
  frontend/src/assets/tmp/images/banner4.png
  frontend/src/components/CommonBanner.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/PhoneAuthAPI.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/layouts/user/DefaultLayout.vue
  frontend/src/utils/image.ts
  frontend/src/utils/validation.ts
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 프론트엔드, 디자인

#304 Fix/303(사용자 및 프로필 관련 오류 처리)
  backend/src/main/java/woorifisa/goodfriends/backend/user/domain/User.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/ProfileFixtures.java
Labels: 백엔드, 버그 처리, 테스트

#306 Fix/305(빌드 오류 수정)
  frontend/src/components/PhoneAuthAPI.vue
Labels: 프론트엔드, 버그 처리

#307 Refactor/301(주문 API 리펙토링)
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/exception/NotOwnProductException.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/exception/OwnProductException.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java
  frontend/src/components/OrderModal.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
Labels: 리팩터링, 프론트엔드, 백엔드

#310 Refactor/309(sameSite 설정을 위해 ResponseCookie 형으로 변환)
  backend/src/main/java/woorifisa/goodfriends/backend/auth/application/AuthTokenResponseHandler.java
Labels: 리팩터링, 백엔드

#311 Feature/308(주문서를 선택한 경우 주문서 보기 페이지에서 해당 주문서만 확인)
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/OrderRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/dto/response/OrderViewAllResponse.java
  frontend/src/apis/user/order.ts
  frontend/src/components/ConfirmModal.vue
  frontend/src/constants/strings/product.ts
  frontend/src/types/order.ts
  frontend/src/views/user/OrderView.vue
Labels: 프론트엔드, 기능, 백엔드

#313 Refactor/312(프론트엔드 코드 리펙토링)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/index.ts
  frontend/src/apis/user/login.ts
  frontend/src/apis/user/order.ts
  frontend/src/apis/user/product.ts
  frontend/src/apis/user/profile.ts
  frontend/src/apis/user/report.ts
  frontend/src/components/OrderModal.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/strings/error.ts
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/router/index.ts
  frontend/src/utils/file.ts
  frontend/src/views/admin/AdminLogin.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/profile/ProfileView.vue
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
  frontend/vite.config.ts
Labels: 리팩터링, 프론트엔드, 기능, 디자인

#317 Fix/314(timeout 시간 변경)
  frontend/src/apis/index.ts
  frontend/src/apis/user/order.ts
  frontend/src/components/product/EditProduct.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 프론트엔드, 버그 처리

#319 Refactor/316(동일한 상품을 중복 신고할 수 없도록 기능 수정)
  backend/src/main/java/woorifisa/goodfriends/backend/global/error/ControllerAdvice.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/application/ReportService.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/domain/ReportRepository.java
  backend/src/main/java/woorifisa/goodfriends/backend/report/exception/AlreadyReportedException.java
  frontend/src/components/CommonBanner.vue
Labels: 리팩터링, 백엔드

#322 Feature/315(거래완료 프로세스 구현)
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/domain/ConfirmStatus.java
  backend/src/main/java/woorifisa/goodfriends/backend/order/presentation/OrderController.java
  frontend/src/apis/admin/allUserInfo.ts
  frontend/src/apis/user/order.ts
  frontend/src/components/ProductCard.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/constants/strings/product.ts
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/profile/PurchaseView.vue
Labels: 리팩터링, 프론트엔드, 기능, 디자인, 백엔드

#321 Feature/318(프로필 배너 수정)
  frontend/src/apis/user/profile.ts
  frontend/src/assets/images/banCount.png
  frontend/src/assets/images/dealCount.png
  frontend/src/assets/images/verifiedBadge.png
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/constants/strings/profile.ts
  frontend/src/router/index.ts
  frontend/src/types/profile.ts
  frontend/src/views/user/profile/ProfileView.vue
  frontend/src/views/user/profile/PurchaseView.vue
  frontend/src/views/user/profile/SellView.vue
Labels: 프론트엔드, 기능, 디자인

#325 Feature/323(비활성화된 유저의 상품 조회 불가)
  backend/src/main/java/woorifisa/goodfriends/backend/admin/application/AdminService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/application/ProductService.java
  backend/src/main/java/woorifisa/goodfriends/backend/product/dto/response/ProductViewAllResponse.java
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/ProductFixtures.java
Labels: 기능, 백엔드

#327 fix/326(상품 전체 조회 테스트 코드 에러를 해결)
  backend/src/test/java/woorifisa/goodfriends/backend/common/fixtures/UserFixtures.java
  backend/src/test/java/woorifisa/goodfriends/backend/product/application/ProductServiceTest.java
Labels: 백엔드, 긴급(Hotfix), 테스트

#324 Refactor/320(메인페이지 배너 및 CSS 수정)
  frontend/src/assets/images/404_error.png
  frontend/src/assets/images/banner.png
  frontend/src/assets/images/banner1.png
  frontend/src/assets/images/banner2.png
  frontend/src/components/CategoryList.vue
  frontend/src/components/CommonBanner.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/router/index.ts
  frontend/src/utils/image.ts
  frontend/src/views/user/HomeView.vue
Labels: 리팩터링, 프론트엔드, 디자인

#329 328/Refactor(배너 이미지 디자인 수정)
  frontend/src/assets/images/banner2.png
  frontend/src/components/CommonBanner.vue
Labels: 리팩터링, 프론트엔드, 디자인

#331 Style/330(소개 페이지 구현)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/alarm-icon.png
  frontend/src/assets/images/arrow.png
  frontend/src/assets/images/glass-icon.png
  frontend/src/assets/images/handshake-icon.png
  frontend/src/assets/images/security-icon.png
  frontend/src/components/threes/BallDrop.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/user/AboutView.vue
Labels: 프론트엔드, 디자인

#334 Feature/332( 접근성 및 SEO 개선 )
  frontend/index.html
  frontend/src/apis/admin/adminProduct.ts
  frontend/src/apis/admin/allUserInfo.ts
  frontend/src/assets/images/blog.png
  frontend/src/assets/images/github.png
  frontend/src/components/CategoryList.vue
  frontend/src/components/ConfirmModal.vue
  frontend/src/components/OrderModal.vue
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/layouts/user/DefaultHeader.vue
  frontend/src/views/user/AboutView.vue
  frontend/src/views/user/BoardReportView.vue
  frontend/src/views/user/ErrorView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/NotFoundView.vue
  frontend/src/views/user/OrderView.vue
  frontend/src/views/user/ProductView.vue
  frontend/src/views/user/profile/ProfileView.vue
Labels: 리팩터링, 프론트엔드, 기능

#335 Refactor/333(미사용 css 삭제)
  frontend/index.html
  frontend/src/apis/admin/adminProduct.ts
  frontend/src/components/ConfirmModal.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/ProductDetailByAdmin.vue
  frontend/src/components/product/EditProduct.vue
  frontend/src/components/profile/DefaultMyPage.vue
  frontend/src/components/profile/ItemList.vue
  frontend/src/components/threes/BallDrop.vue
  frontend/src/constants/strings/product.ts
  frontend/src/layouts/admin/DefaultSide.vue
  frontend/src/views/admin/AddProductByAdminView.vue
  frontend/src/views/admin/DeclarationDetailView.vue
  frontend/src/views/admin/EditProductByAdminView.vue
  frontend/src/views/admin/EditUserInfoView.vue
  frontend/src/views/admin/ManageLogView.vue
  frontend/src/views/admin/ManageProductView.vue
  frontend/src/views/admin/ManageUserView.vue
  frontend/src/views/user/BoardReportView.vue
  frontend/src/views/user/HomeView.vue
  frontend/src/views/user/ProductView.vue
Labels: 리팩터링, 프론트엔드

#337 Fix/336(거래할 구매자 선택시 주문서 안보이는 문제를 해결)
  backend/src/main/java/woorifisa/goodfriends/backend/order/application/OrderService.java
Labels: 백엔드, 버그 처리

#341 Readme/340(리드미 최신화로 수정)
  README.md
  docs/service_introduction.png
Labels: 문서 작성
